### ISSUE TITLE
SumOne com problema?

### ISSUE THREAD

**Issue by LuccaHiratsuca** [Insper/ai_gym#15]
<img width="1151" alt="image" src="https://github.com/Insper/ai_gym/assets/104103173/14722069-5ce3-49fd-be65-9bc6bba37284">

# Quanto maior o objetivo, menor o tempo de processamento? 
- Algoritmo utilizado: Busca em Profundidade Iterativa

Dado que o tempo nesse algoritmo é dado por bˆd, o algoritmo deveria aumentar o tempo de processamento, conforme o aumento da camada de busca. E não o contrário, conforme ilustrado na imagem acima.

**Comment by fbarth** [comment]
este comportamento acontece pq enquanto rodamos o algoritmo o computador está fazendo outras coisas e isso interfere no tempo de processamento.

**Comment by alessitomas** [comment]
Sim, o algoritmo deve apresentar um tempo maior de processamento, para tarefas de busca que visitam mais nodos que outras. Nesse caso, como evidenciado no print isso não é verificado causando a dúvida. Isso se deve ao baixo tempo de processamento das tarefas (68009 microsegundo ~ 0.068009 segundos). Enquanto você roda o programa seu processador está ocupado com outras tarefas também, e isso será capaz de interferir nos microsegundos do processamento.
