### ISSUE TITLE
Não encontra nenhuma solução quando informado um método de pruning que não existe

### ISSUE THREAD

**Issue by fbarth** [Insper/ai_gym#16]
Considere o seguinte código: 

```python
state = SumOne(1, '', 11)
algorithm = BuscaLargura()
result = algorithm.search(state, pruning='father')
```
O nome do método de pruning foi digitado de forma incorreta. Neste caso, result será igual a None. É este o comportamento desejado?

**Comment by fbarth** [comment]
Pode mandar como pull request, por favor.

**Comment by alessitomas** [comment]
Adicionei um Pull request agora (Pruning names validation). Como o git teve updates agora, eu criei uma nova branch atualizada para essa implementação e passei as atualizações para ela. Para o pull request ir sem problemas de merge.
