### ISSUE TITLE
Deixar os algoritmos (SumOne, Aspirador de Pó e POI)  já implementados em `./tests`

### ISSUE THREAD

**Issue by LuccaHiratsuca** [Insper/ai_gym#40]
Considerando as próximas turmas, não seria melhorar não deixar os algoritmos (SumOne, Aspirador de Pó e POI) implementados em `./tests`? Uma vez que, ao longo da disciplina, esses devem ser implementados pelos alunos.

**Comment by fbarth** [comment]
Estes são exercícios bem básicos. A ideia é justamente deixar como exemplo.
