### ISSUE TITLE
Implementar sugestões do pylint para o arquivo Graph.py

### ISSUE THREAD

**Issue by fbarth** [Insper/ai_gym#52]
(venv) ➜  search git:(main) ✗ pylint Graph.py 
************* Module aigyminsper.search.Graph
Graph.py:28:78: C0303: Trailing whitespace (trailing-whitespace)
Graph.py:31:0: C0303: Trailing whitespace (trailing-whitespace)
Graph.py:43:0: C0303: Trailing whitespace (trailing-whitespace)
Graph.py:44:0: C0303: Trailing whitespace (trailing-whitespace)
Graph.py:65:0: C0303: Trailing whitespace (trailing-whitespace)
Graph.py:72:0: C0303: Trailing whitespace (trailing-whitespace)
Graph.py:79:0: C0303: Trailing whitespace (trailing-whitespace)
Graph.py:98:0: C0304: Final newline missing (missing-final-newline)
Graph.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Graph.py:1:0: C0103: Module name "Graph" doesn't conform to snake_case naming style (invalid-name)
Graph.py:16:11: C0121: Comparison 'self.father_node == None' should be 'self.father_node is None' (singleton-comparison)
Graph.py:27:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
Graph.py:27:11: C0121: Comparison 'self.father_node != None' should be 'self.father_node is not None' (singleton-comparison)
Graph.py:64:8: W0107: Unnecessary pass statement (unnecessary-pass)
Graph.py:71:8: W0107: Unnecessary pass statement (unnecessary-pass)
Graph.py:78:8: W0107: Unnecessary pass statement (unnecessary-pass)
Graph.py:85:8: W0107: Unnecessary pass statement (unnecessary-pass)
Graph.py:91:19: E1101: Instance of 'State' has no 'operator' member (no-member)
Graph.py:98:8: W0107: Unnecessary pass statement (unnecessary-pass)

-----------------------------------
Your code has been rated at 2.58/10

**Comment by fbarth** [comment]
Now, the status is: 

pylint Graph.py                                 
************* Module aigyminsper.search.Graph
Graph.py:1:0: C0103: Module name "Graph" doesn't conform to snake_case naming style (invalid-name)
Graph.py:88:19: E1101: Instance of 'State' has no 'operator' member (no-member)

------------------------------------------------------------------
Your code has been rated at 7.69/10 (previous run: 7.69/10, +0.00)

**Comment by leoscarlato** [comment]
Professor, agora acredito que esteja correto.
